### PR TITLE
java.io.NotSerializableException from AWSResponseException

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-51390](https://issues.jenkins-ci.org/browse/JENKINS-51390)

https://github.com/jenkinsci/workflow-support-plugin/pull/61 is the workaround; the real fix is in https://github.com/jclouds/jclouds/pull/1211.

### CODE REVIEW

**Comment by carlossg** [comment]
should RuntimeException be caught in the API instead of forcing plugins to catch it ?

**Comment by jglick** [comment]
> should RuntimeException be caught in the API instead of forcing plugins to catch it ?

Which API? jclouds?

**Comment by carlossg** [comment]
no, jenkins core

**Comment by jglick** [comment]
Then I am not sure which API you are referring to. `ArtifactManager.delete` perhaps, but the stash-related APIs are defined in `workflow-api`.

**Comment by jglick** [comment]
Build will fail since upstream is still waiting in queue: [INFRA-1633](https://issues.jenkins-ci.org/browse/INFRA-1633).

**Pull request merged**
