### PR TITLE
[JENKINS-66984] Pick up newer Guava from core

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-66984](https://issues.jenkins.io/browse/JENKINS-66984)

Downstream of https://github.com/jenkinsci/jenkins/pull/5707.

#215 and #226 might need to wait for a Guice upgrade.

See e.g. #140 for motivation.

### CODE REVIEW

**Comment by jglick** [comment]
> wait for a Guice upgrade

https://github.com/jenkinsci/jenkins/pull/5858 FTR

**Comment by car-roll** [comment]
@jglick can we get a new release on this? PCT fails on `NetworkTest` without these changes

**Comment by jglick** [comment]
OK. It looks like https://github.com/jenkinsci/jenkins/pull/5858 has been released, too, so I can try taking advantage of that next.

**Comment by jglick** [comment]
https://github.com/jenkinsci/artifact-manager-s3-plugin/releases/tag/artifact-manager-s3-1.17

**Pull request merged**
