### PR TITLE
[CPLT2-5579] Flush logger after remoting call to make sure logging ap…

### PR DESCRIPTION
**Pull request by Vlatombe**
…pears

cc @jglick

### CODE REVIEW

**Comment by batmat** [comment]
@Vlatombe for the Javadoc issue, please bump to parent 3.43. Thanks for this!

**Comment by batmat** [comment]
@jenkinsci/java11-support fyi

**Comment by jglick** [comment]
> please do not use internal tickets in PRs

Well, better than nothing. In this case it seems the issue is a PCT failure. But that was already supposed to have been fixed in #92, released as 1.5, so I need to investigate why there are still test failures. This patch does not smell right.

**Comment by Vlatombe** [comment]
#92 only covered success case, not exception cases

**Comment by jglick** [comment]
> somehow got merged anyway

Did @oleg-nenashev somehow release 1.5 without running tests?

**Pull request merged**
