### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by jglick**
Subsumes #91. @richbg

### CODE REVIEW

**Comment by jglick** [comment]
> Some unrelated WS changes afaict

Where? I had to fix an import after a package rename of a dep.

**Comment by batmat** [comment]
Cannot see anything anymore about WS changes at the bottom. Given there's nothing anymore, I'm going to assume either I was drunk, or GitHub UI was getting crazy, or both.
Anyway, bottom line is that we're fine and even more good to go \o/.

Thanks

**Comment by batmat** [comment]
@jenkinsci/java11-support FYI

**Comment by oleg-nenashev** [comment]
Cutting a release right now. Will be in 1.5

**Comment by oleg-nenashev** [comment]
@jglick https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/92/commits/9da949541b8a9c5cb36a290fa8a4f91f92132b6f is not clear to me. Is it a separate bugfix? Does it need a changelog?

**Comment by jglick** [comment]
It is the fix for the minor regression that PCT uncovered.

**Pull request merged**
